apiVersion: v1
kind: Secret
metadata:
  name: timelycabs-secrets
  namespace: timelycabs
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  DATABASE_URL: bXlzcWwrcHlteXNxbDovL3VzZXJuYW1lOnBhc3N3b3JkQGxvY2FsaG9zdDozMzA2L3RpbWVseWNhYnM=
  SECRET_KEY: eW91ci1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9u
  SMS_API_KEY: eW91ci1zbXMtYXBpLWtleQ==
  SMS_API_SECRET: eW91ci1zbXMtYXBpLXNlY3JldA==
  REDIS_URL: cmVkaXM6Ly9sb2NhbGhvc3Q6NjM3OS8w
